package tau.literal;

public enum TType {
	LEFT_BRACE, RIGHT_BRACE, LEFT_PAREN, RIGHT_PAREN,
	COMMA, DOT, COLON, HASHTAG, SLASH, STAR, PLUS,
	MINUS, EQUAL, EQUAL_EQUAL, BANG, BANG_EQUAL,
	GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
	IDENTIFIER, STRING, NUMBER, AT,
	DEFMAP, DEFFUN, DEFM, DEFTYPE, LET, AND, OR,
	TRUE, DEL, FALSE, WHILE, IF, ELSE, SEMICOLON, 
	EOF, NONE, RETURN, DEBUG, DO, END, MATCH, CASE,
	DEFAULT, LEFT_BRACK, RIGHT_BRACK, IMPORT,
	DOUBLE_LBRACK, DOUBLE_RBRACK, DEFENUM, PIPE
}
